version: '3'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.30
    environment:
      - http_proxy
      - MEILI_MASTER_KEY=xcz
      - MEILI_ENV=development
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=/meili_data
    ports:
      - 7700:7700
    networks:
      - website
    volumes:
      - ./meilisearch/meili_data:/meili_data
    restart: unless-stopped
  
  vue_nginx:
    container_name: vue_nginx
    depends_on:
      - meilisearch
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - website
    restart: unless-stopped

networks:
  website:
    driver: bridge